### ISSUE TITLE
Loop on dictionaries

### ISSUE THREAD

**Issue by jmrgonza** [uwefladrich/scriptengine#47]
I think that it would be an interesting feature to add an option to use dictionaries for loops. I think that the current implementation only allows to use lists (mapping their elements by default to an item argument), and I propose to implement loops on dictionaries (mapping the keys and values contained in the dictionary).

**Comment by uwefladrich** [comment]
Hi,
It took me a while because the change had consequences for the user interface and also because it turned out that I should do some reshuffling of deeper code layers. This improved the SE structure quite a bit, so good that it's done!

I merged the changes into master, but beware that the automatic testing figured out a problem with Python3.6! So if you are using this version, stick to the last released version 0.11!

Documentation is updated with the loop-over-dict changes!
